Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -78,6 +78,18 @@ jobs:
       - name: Build with Next.js
         working-directory: portfolio
         run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      - name: Create out directory and copy files
+        working-directory: portfolio
+        run: |
+          if [ -d ./portfolio/.next ]; then
+            mkdir -p ./out
+            cp -r ./portfolio/.next ./out/.next
+            cp -r ./portfolio/public ./out/public
+            cp ./portfolio/package.json ./out/package.json
+          else
+            echo "Build failed or .next directory not found. Exiting..."
+            exit 1
+          fi
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with: 
